// <auto-generated />
using System;
using LibraryManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Infrastructure.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260905065513_CreateMembersTable")]
    partial class CreateMembersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Course")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Department")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Designation")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<int>("MaxBooksAllowed")
                        .HasColumnType("int");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Semester")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasFilter("[RegistrationNumber] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Members", null, t =>
                        {
                            t.HasCheckConstraint("CK_Members_FacultyFields", "[MembershipType] <> 'Faculty' OR ([Designation] IN ('Professor', 'Associate Professor', 'Assistant Professor', 'Lecturer', 'Senior Lecturer', 'Visiting Faculty', 'Guest Faculty', 'Adjunct Faculty', 'HOD', 'Dean') AND [Department] IN ('CSE', 'ECE', 'EEE', 'ME', 'CE', 'IT', 'MBA', 'MCA'))");

                            t.HasCheckConstraint("CK_Members_MaxBooksAllowed", "([MembershipType] = 'Student' AND [MaxBooksAllowed] = 5) OR ([MembershipType] = 'Faculty' AND [MaxBooksAllowed] = 8)");

                            t.HasCheckConstraint("CK_Members_MembershipType", "[MembershipType] IN ('Student', 'Faculty')");

                            t.HasCheckConstraint("CK_Members_StudentCourse", "[MembershipType] <> 'Student' OR ([Course] IN ('BTech CSE', 'BTech IT', 'BTech ECE', 'BTech EEE', 'BTech ME', 'BTech CE', 'MCA', 'MBA', 'MTech CSE', 'MTech IT', 'MTech ECE', 'MTech EEE', 'MTech ME', 'MTech CE') AND (([Course] IN ('MCA', 'MBA') AND [Semester] IN ('I', 'II', 'III', 'IV')) OR ([Course] LIKE 'BTech %' AND [Semester] IN ('I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII')) OR ([Course] LIKE 'MTech %' AND [Semester] IN ('I', 'II', 'III', 'IV'))))");

                            t.HasCheckConstraint("CK_Members_StudentFields", "([MembershipType] = 'Student' AND [RegistrationNumber] IS NOT NULL AND LEN([RegistrationNumber]) BETWEEN 12 AND 14 AND [Course] IS NOT NULL AND [Semester] IS NOT NULL AND [EmployeeId] IS NULL AND [Designation] IS NULL AND [Department] IS NULL) OR ([MembershipType] = 'Faculty' AND [EmployeeId] IS NOT NULL AND LEN([EmployeeId]) BETWEEN 6 AND 8 AND [Designation] IS NOT NULL AND [Department] IS NOT NULL AND [RegistrationNumber] IS NULL AND [Course] IS NULL AND [Semester] IS NULL)");
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('Admin', 'Librarian', 'Student', 'Faculty')");
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Member", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.User", "User")
                        .WithOne("Member")
                        .HasForeignKey("LibraryManagement.Domain.Entities.Member", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
